---
- name: debian | Installing DRBD packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ drbd_deb_packages }}"

- name: debian | Installing Heartbeat Package
  apt:
    name: heartbeat
    state: present
  become: true
  when: cron_apt_configure

- name: debian | Installing NFS-Kernel-Server Package
  apt:
    name: nfs-kernel-server
    state: present
  become: true
  when: drbd_ha_nfsserver == true
