---
- name: services | Ensuring drbd Service Is Enabled On Boot
  service:
    name: drbd
    enabled: true
  become: true

- name: services | Ensuring heartbeat Service Is Enabled On Boot
  service:
    name: heartbeat
    enabled: true
  become: true
  when: drbd_use_heartbeat

- name: services | Ensuring nfs-kernel-server Service Is stopped On Boot
  service:
    name: nfs-kernel-server
    enabled: false
  become: true
  when: drbd_ha_nfsserver == true

