---
- name: services | Ensuring drbd Service Is Enabled On Boot
  service:
    name: drbd
    enabled: true
  become: true

- name: services | Ensuring heartbeat Service Is Enabled On Boot
  service:
    name: heartbeat
    enabled: true
  become: true
  when: drbd_use_heartbeat

- name: services | Ensuring Monitored Service Is Stopped On Boot
  service:
    name: "{{ drbd_ha_servicename }}"
    enabled: false
  become: true
  when: drbd_ha_service == true and drbd_ha_servicename is defined

