---
# handlers file for ansible-role-drbd
- name: restart drbd
  service:
    name: drbd
    state: restarted
  become: true

- name: restart heartbeat
  service:
    name: heartbeat
    state: restarted
  become: true
